[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "xilophor"
name = "BestScoreBoards"
description = "Keep your best score on the leaderboard, not your latest!"
websiteUrl = ""
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../BestScoreBoards/bin/Release/netstandard2.1/BestScoreBoards.dll"
target = "/BepInEx/plugins/BestScoreBoards/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "bepinex", "mods", "clientside" ]